POST http://localhost:3003/api/blogs 
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMTYyMGE0NWExMzRlNjI5ZTM5Njk0ZiIsInVzZXJuYW1lIjoibWF0aWI4MyIsImlhdCI6MTY2MjU1MTU3MywiZXhwIjoxNjYzMTU2MzczfQ.66mn_VeR_SUPRAu7f7eCe6Kn_2S1tiu63OLaUdNdiQQ

{
  "title": "Probando nueva forma de ver los datos",
  "author": "Uknown",
  "url": "N/A"
}

###  

// Antes de tener el Token de un usuario, para poder crear un blog era necesario pasar el ID
// del mismo en el body como un campo.

POST http://localhost:3003/api/blogs
Content-type: application/json

{
  "title": "El tunel",
  "author": "Sabato Ernesto",
  "url": "http://blog.matib83.com/ElTunel",
  "userId": "631620a45a134e629e39694f"
}